# Generated by Django 5.1.3 on 2024-12-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentlist',
            name='deadline',
            field=models.DateField(auto_now_add=True),
        ),
    ]
