# Generated by Django 5.1.3 on 2024-12-17 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_assignmentlist_assignment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='sent_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 17, 23, 9, 48, 424077), null=True),
        ),
    ]
