# Generated by Django 5.1.3 on 2024-12-18 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_assignmentlist_assignment_file_assignmentlist_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='sent_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 18, 11, 50, 49, 862552), null=True),
        ),
        migrations.AlterField(
            model_name='assignmentlist',
            name='assignment_file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
