# Generated by Django 5.1.3 on 2024-12-18 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_assignment_sent_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='assignment_id',
            new_name='assignment_id2',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='sent_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 18, 12, 23, 34, 58710), null=True),
        ),
    ]
