# Generated by Django 5.1.3 on 2024-12-18 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_assignment_id_assignment_assignment_id2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='sent_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 18, 12, 29, 35, 345012), null=True),
        ),
    ]
