# Generated by Django 5.1.3 on 2024-12-25 05:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_assignment_sent_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='sent_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 25, 10, 55, 16, 236326), null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='menterList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentorName', models.TextField(blank=True, max_length=200, null=True)),
                ('qualification', models.TextField(blank=True, max_length=200, null=True)),
                ('mentorUnderStd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
