# Generated by Django 5.1.3 on 2024-12-14 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='Question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Question', to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Catagory', to='quiz.catagory'),
        ),
    ]
