# Generated by Django 5.1.3 on 2024-12-08 16:59

import loginapp.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_catagory_alter_customeruser_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customeruser',
            managers=[
                ('objects', loginapp.manager.usermanager()),
            ],
        ),
    ]
