# Generated by Django 5.1.3 on 2024-12-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_alter_customeruser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
