# Generated by Django 5.1.3 on 2024-12-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0005_alter_customeruser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
