# Generated by Django 5.1 on 2024-09-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_resumemodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumemodel',
            name='gender',
            field=models.CharField(max_length=100),
        ),
    ]
