# Generated by Django 5.1 on 2024-09-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_resumemodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumemodel',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=100),
        ),
    ]
