# Generated by Django 5.1.1 on 2024-09-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_resumemodel_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumemodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='resumemodel',
            name='job_city',
        ),
        migrations.RemoveField(
            model_name='resumemodel',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='resumemodel',
            name='state',
        ),
        migrations.AddField(
            model_name='resumemodel',
            name='experience',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], default=False),
        ),
        migrations.AddField(
            model_name='resumemodel',
            name='hobbies',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resumemodel',
            name='languagies',
            field=models.CharField(choices=[('Bengali', 'Bengali'), ('English', 'English'), ('Hindi', 'Hindi'), ('French', 'French')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resumemodel',
            name='objective',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resumemodel',
            name='skill',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
