# Generated by Django 5.1.1 on 2024-09-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_remove_resumemodel_city_remove_resumemodel_job_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumemodel',
            name='experience',
            field=models.CharField(max_length=100),
        ),
    ]
