# Generated by Django 5.1.3 on 2024-12-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_resumemodel_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumemodel',
            name='languagies',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
