# Generated by Django 5.1.3 on 2024-12-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_alter_resumemodel_languagies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumemodel',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
